### ISSUE TITLE
Drop ROS Melodic support

### ISSUE THREAD

**Issue by Tiryoh** [Tiryoh/docker-ros-desktop-vnc#38]
![image](https://github.com/Tiryoh/docker-ros-desktop-vnc/assets/3256629/f3135125-2282-4ecb-843f-19c303d9b3f8)

* https://wiki.ros.org/Distributions
* https://twitter.com/OpenRoboticsOrg/status/1673707563580555264?s=20

**Comment by Tiryoh** [comment]
Due to the following message during the installation step, I'll stop the GitHub Actions for Melodic.

`pkg_resources.DistributionNotFound: The 'importlib_metadata' distribution was not found and is required by rosdep`

```
#8 287.9 Traceback (most recent call last):
#8 287.9   File "/usr/bin/rosdep", line 6, in <module>
#8 287.9     from pkg_resources import load_entry_point
#8 287.9   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
#8 287.9     @_call_aside
#8 287.9   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
#8 287.9     f(*args, **kwargs)
#8 287.9   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
#8 287.9     working_set = WorkingSet._build_master()
#8 287.9   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
#8 287.9     ws.require(__requires__)
#8 287.9   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 892, in require
#8 287.9     needed = self.resolve(parse_requirements(requirements))
#8 287.9   File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 778, in resolve
#8 287.9     raise DistributionNotFound(req, requirers)
#8 287.9 pkg_resources.DistributionNotFound: The 'importlib_metadata' distribution was not found and is required by rosdep
```

https://github.com/Tiryoh/docker-ros-desktop-vnc/actions/runs/8954967020
